dependencies:
  - name: elasticsearch
    repository: file://../../
    version: 6.6.0-alpha1
    alias: es-data
  - name: elasticsearch
    repository: file://../../
    version: 6.6.0-alpha1
    alias: es-master
